from fastapi_mail import ConnectionConfig, FastMail, MessageSchema, MessageType
from app.core.config import get_settings
from pydantic import EmailStr
import os

settings = get_settings()

conf = ConnectionConfig(
    MAIL_USERNAME=settings.mail_username,
    MAIL_PASSWORD=settings.mail_password,
    MAIL_FROM=settings.mail_from,
    MAIL_PORT=settings.mail_port,
    MAIL_SERVER=settings.mail_server,
    MAIL_FROM_NAME=settings.mail_from_name,
    MAIL_STARTTLS=True,
    MAIL_SSL_TLS=False,
    USE_CREDENTIALS=True,
    VALIDATE_CERTS=True
)

def get_order_html_template(order: dict, items: list, is_company: bool = False) -> str:
    items_html = ""
    for item in items:
        price = item.get('price', 0)
        quantity = item.get('quantity', 1)
        name = item.get('product_name', 'Unknown Product')
        items_html += f"""
        <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">{name}</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee; text-align: center;">{quantity}</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee; text-align: right;">Rs. {price:,.2f}</td>
            <td style="padding: 12px; border-bottom: 1px solid #eee; text-align: right;">Rs. {price * quantity:,.2f}</td>
        </tr>
        """

    title = "New Order Received" if is_company else "Order Confirmation"
    greeting = f"A new order has been placed by {order.get('customer_name')}." if is_company else f"Hello {order.get('customer_name')}, thank you for your order!"
    
    order_id = order.get('id', 'N/A')

    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body {{ font-family: 'Inter', Arial, sans-serif; line-height: 1.6; color: #333; margin: 0; padding: 0; }}
            .container {{ max-width: 600px; margin: 20px auto; border: 1px solid #eee; border-radius: 8px; overflow: hidden; }}
            .header {{ background: #000; color: #fff; padding: 30px; text-align: center; }}
            .content {{ padding: 30px; }}
            .footer {{ background: #f9f9f9; padding: 20px; text-align: center; font-size: 12px; color: #888; }}
            .order-table {{ width: 100%; border-collapse: collapse; margin-top: 20px; }}
            .order-table th {{ background: #f4f4f4; padding: 12px; text-align: left; font-size: 14px; }}
            .summary {{ margin-top: 20px; text-align: right; }}
            .summary-item {{ margin-bottom: 5px; }}
            .total {{ font-size: 18px; font-weight: bold; color: #000; margin-top: 10px; }}
            .customer-info {{ background: #f9f9f9; padding: 15px; border-radius: 6px; margin-bottom: 20px; }}
            .order-id-badge {{ background: #eee; padding: 5px 10px; border-radius: 4px; font-family: monospace; font-size: 13px; }}
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1 style="margin: 0; letter-spacing: 2px;">NAWAB</h1>
                <p style="margin: 10px 0 0 0; opacity: 0.8;">{title}</p>
            </div>
            <div class="content">
                <h3>{greeting}</h3>
                <p><strong>Order ID:</strong> <span class="order-id-badge">{order_id}</span></p>
                
                <div class="customer-info">
                    <strong>Customer & Shipping Details:</strong><br>
                    Name: {order.get('customer_name')}<br>
                    <strong>Phone: {order.get('customer_phone')}</strong><br>
                    Email: {order.get('customer_email')}<br>
                    Address: {order.get('shipping_address')}, {order.get('city')}
                </div>

                <strong>Order Summary:</strong>
                <table class="order-table">
                    <thead>
                        <tr>
                            <th>Product</th>
                            <th style="text-align: center;">Qty</th>
                            <th style="text-align: right;">Price</th>
                            <th style="text-align: right;">Subtotal</th>
                        </tr>
                    </thead>
                    <tbody>
                        {items_html}
                    </tbody>
                </table>

                <div class="summary">
                    <div class="summary-item">Payment Method: {order.get('payment_method')}</div>
                    <div class="total">Total Amount: Rs. {float(order.get('total_amount', 0)):,.2f}</div>
                </div>
            </div>
            <div class="footer">
                &copy; 2026 Nawab Store. All rights reserved.<br>
                This is an automated message generated by the Nawab E-commerce System.
            </div>
        </div>
    </body>
    </html>
    """

async def send_order_confirmation(order: dict, items: list):
    """
    Sends order confirmation email to both user and company.
    """
    if not settings.mail_username or not settings.mail_password:
        print("⚠️ Mail credentials not configured. Skipping email.")
        return

    user_html = get_order_html_template(order, items, is_company=False)
    company_html = get_order_html_template(order, items, is_company=True)
    
    order_id_short = str(order.get('id', ''))[-6:]
    
    # Send to User
    message_user = MessageSchema(
        subject=f"Order Confirmation - Nawab #{order_id_short}",
        recipients=[order.get('customer_email')],
        body=user_html,
        subtype=MessageType.html
    )

    # Send to Company
    message_company = MessageSchema(
        subject=f"NEW ORDER RECEIVED - Nawab #{order_id_short}",
        recipients=[settings.company_email],
        body=company_html,
        subtype=MessageType.html
    )

    fm = FastMail(conf)
    try:
        await fm.send_message(message_user)
        await fm.send_message(message_company)
        print(f"✅ Order emails sent for order {order.get('id')}")
    except Exception as e:
        print(f"❌ Error sending order emails: {str(e)}")
